import { GlobalStyle } from "/globalStyleds";
import { storeWrapper } from "../store";
import "normalize.css";
import "/components/Product/ProductDescription/CKEditorContentStyles.css"
import Head from 'next/head'

function MyApp({ Component, pageProps }) {

  const getLayout = Component.getLayout || ((page) => page)
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mercado_delivery_isolated_logo.svg" />
      </Head>
      <GlobalStyle />
      {getLayout(<Component {...pageProps} />)}
    </>
  )
}
export default storeWrapper.withRedux(MyApp)
