import { GlobalStyle } from "@globalStyleds";
import { storeWrapper } from "../store";
import "normalize.css";
import "/components/Product/ProductDescription/CKEditorContentStyles.css"
import Head from 'next/head'
import { ReactElement, ReactNode } from "react";
import { NextPage } from "next";
import { AppProps } from "next/app";
import Modal from "@components/Modal";

type NextPageWithLayout = NextPage & {
  getLayout?: (page: ReactElement) => ReactNode
}

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout
}


function MyApp({ Component, pageProps }: AppPropsWithLayout) {

  const getLayout = Component.getLayout || ((page: ReactElement) => page)

  return (
    <>
      <Head>
        <title>Mercado Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mercado_delivery_isolated_logo.svg" />
      </Head>
      <GlobalStyle />
      <Modal />
  
      {getLayout(<Component {...pageProps} />)}
    </>
  )
}
export default storeWrapper.withRedux(MyApp)
