import Head from 'next/head'
import Image from 'next/image'
import { useSelector } from 'react-redux'
import { storeWrapper } from 'store';
//import styles from '../styles/Home.module.css'
import styled from 'styled-components'
import Header from '../components/Header';
import Home from '../components/Home';

const Title = styled.h1`
  color: green;
`;
const Index = ({ teste }) => {

  const counter = useSelector(rootState => rootState.product.title)


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Home />


    </div>
  )
}

export async function getStaticProps(context) {
  return {
    props: {
      teste: 'leonardo'
    }, // will be passed to the page component as props
  }
}

export default Index
